export const skills = [
  {
    label: 'Front End',
    list: [
      'TypeScript',
      'JavaScript',
      'React',
      'Next.js',
      'Tailwind',
      'SCSS',
      'CSS-in-JS',
      'React Query',
      'Zustand',
      'Redux',
      'WebAssembly',
      'WebGL',
      'UI/UX design',
      'accessibility',
    ],
  },
  {
    label: 'Back End',
    list: [
      'Node.js',
      'Rust',
      'Go',
      'Python',
      'GraphQL',
      'MongoDB',
      'PostgreSQL',
      'API design',
      'microservices',
      'AWS S3',
      'AWS EC2',
      'AWS ECS',
      'AWS Lambda',
      'AWS API Gateway',
      'AWS Amplify',
      'AWS VPC',
      'DigitalOcean',
      'CI/CD',
      'Git',
      'GitHub',
    ],
  },
  {
    label: 'Software',
    list: [
      'Figma',
      'Photoshop',
      'Illustrator',
      'After Effects',
      'Premiere Pro',
      'InDesign',
      'TouchDesigner',
      'Cinema 4D',
    ],
  },
];
