name: Build to branch

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Flatten to build branch
        run: |
          git switch out --
          find . | grep -v "out/**\|.git\b/**" | xargs rm -rf
          mv out/** .
          rm -r out
      - name: Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update build"
          git push origin out --force
          
